server:
  port: 8081

pamelanakano:
  client:
    address:
      url: http://host.docker.internal:8080/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal